### ISSUE TITLE
variable storage not possible

### ISSUE THREAD

**Issue by lilyanB** [massalabs/massa-eth-bridge#1]
Here is my problem:
I want to save a swap here : https://github.com/massalabs/massa-eth-bridge/blob/main/Massa/smart-contract/assembly/contracts/main.ts#L227
In the test files you will find the function "open" which I activate.
You can see my tests:
https://github.com/massalabs/massa-eth-bridge/blob/main/Massa/smart-contract/assembly/__tests__/massa-example.spec.ts
here is a screenshot of my tests:
![image](https://user-images.githubusercontent.com/91454320/218863669-b471170d-1828-43b1-b1da-0c4d08ff7628.png)

I don't understand why my variable is not stored

**Comment by peterjah** [comment]
Your issue is that `PersistentMap` does not really support uint8Array as value.
If you look at the `get` function here:
https://github.com/massalabs/massa-as-sdk/blob/6aeb063da2b20ca3366b339cd3800681d84f3e4d/assembly/collections/persistentMap.ts#L163
I the requested value is uInt8Array, it will always return null
As a workaround you can use string values (PersistentMap<string, string>)
I fixed your code to pass the first test in this branch:
https://github.com/massalabs/massa-eth-bridge/blob/fix_persistantMap/Massa/smart-contract/assembly/contracts/main.ts
